title: Changing college cost from 1997 to 2012
subtitle: Benjamin Skinner and Will Doyle
siteurl: /collegecost
github: https://github.com/btskinner/collegecost
mail: btskinner@virginia.edu

date_format: "%d %B %Y"

google_analytics: UA-63981025-1
disqus_shortname:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'footnotes']
permalink:    pretty


